Fixed tests for Python 2.6
* tests.searchcommands are skipped when running under Python 2.6
  Rationale:
  - Search commands require Splunk's Python which has been at 2.7 since Splunk 4.3
  - Search commands should be tested outside of splunk using "splunk cmd python <command-line>
* Test fixes eliminate (1) DeprecationWarning messages regarding use of BaseException.message and (2) a break introduced these past few days.
* TODO: Track down six cookie authentication failures, each with the same failure:
  AttributeError: 'TestCookieAuthentication' object has no attribute assertIsNotNone'
* VERIFIED: No Linux or OS X breaks on Python 2.7